export const SET_COIN_DATA = 'SET_COIN_DATA';
export const ADD_OR_REMOVE_TO_WATCHLIST = 'ADD_OR_REMOVE_TO_WATCHLIST';
export const SET_CHECKED_COIN_ID = 'SET_CHECKED_COIN_ID';
export const ADD_TO_STATE_OPEN_COIN_DATA = 'ADD_TO_STATE_OPEN_COIN_DATA';
export const BACK_FROM_OPEN_COIN = 'BACK_FROM_OPEN_COIN';